config/routes.rb
Rails.application.routes.draw do

root 'trips#index'

resources :trips do
  resources :locations do
    resources :addresses
  end
end

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :location
  
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :addresses, dependent: :destroy
  belongs_to :trip
  validates_presence_of :name
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  has_many :locations, dependent: :destroy
  validates_presence_of :name
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
   def index
    @location = Location.find(params[:location_id])
    @addresses = @location.items
  end

  def show
  end

  def new
    @location = Location.find(params[:location_id])
    @address = Address.new
  end

  def create
    @location = Location.find(params[:location_id])
    @location.addresses.create(address_params)
    redirect_to trip_location_addresses_path(@location.trip, @location)
  end

  def edit
  end

  def update
  end

  private
  def item_params
    params.require(:address).permit(:street, :city, :state, :zip, :country)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @trip = Trip.find(params[:trip_id])
    @locations = @trip.locations
  end

  def show
    @location = Location.find(params[:id])
  end

  def edit
  end

  def new
    @trip = Trip.find(params[:trip_id])
    @location = Location.new
  end

  def create
    @trip = Trip.find(params[:trip_id])
    @trip.locations.create(location_params)
    redirect_to trip_location_path(@trip)
  end

  private
    def location_params
      params.require(:location).permit(:name)
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  
  def index
    @trips = Trip.all
  end

  def show
    @trip = Trip.find(params[:id])
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.create(trip_params)
    redirect_to trips_path
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])
    @trip.update(trip_params)
    redirect_to trip_path(@trip)
  end

  def destroy
    @trip.destroy
    redirect_to trips_path
  end

   private
    def trip_params
      params.require(:trip).permit(:name, :start_date, :end_date, :picture, :description)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/addresses/edit.html.erb
<h1>Addresses#edit</h1>
<p>Find me in app/views/addresses/edit.html.erb</p>

app/views/addresses/index.html.erb
<h1>Addresses#index</h1>
<p>Find me in app/views/addresses/index.html.erb</p>

app/views/addresses/new.html.erb
<h1>Addresses#new</h1>
<p>Find me in app/views/addresses/new.html.erb</p>

app/views/addresses/show.html.erb
<h1>Addresses#show</h1>
<p>Find me in app/views/addresses/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TripTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/edit.html.erb
<h1>Locations#edit</h1>
<p>Find me in app/views/locations/edit.html.erb</p>

app/views/locations/new.html.erb
<h1> New Location for <%= @trip.name %> trip</h1>
<hr />

<%= form_for [@trip, @location] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

<hr />

<%= link_to "Back to trips", trips_path %>

app/views/locations/show.html.erb
<h1><%= @trip.name %> Location</h1>
<hr />

<div class = "center">
  <h3><%= @trip.name %></h3>
  <p><small>Dates: <%= @trip.start_date %> through <%= @trip.end_date %></small></p>
  <p><%= @trip.description %></p>
  <footer> <small> <%= link_to 'Add Location', new_trip_location_path(@trip) %> </small> </footer>
<hr />


<footer>
  <small>
  <%= link_to 'Edit Trip', edit_trip_path(@trip) %>

  <%= link_to 'Delete Trip', trip_path(@trip), method: :delete %>
  </small>
</footer>

<br />

<%= link_to "Back to trips", trips_path %>
</div>

app/views/trips/edit.html.erb
<h1>Edit <%= @trip.name %> Trip</h1>
<hr />

<%= form_for @trip do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />
  <%= f.label :start_date %>
  <%= f.text_field :start_date, placeholder: 'DD/MM/YYYY' %>
  <br />
  <%= f.label :end_date %>
  <%= f.text_field :end_date, placeholder: 'DD/MM/YYYY' %>
  <br />
  <%= f.label :description%>
  <%= f.text_field :description %>
  <br />
  <%= f.submit %>
<% end %>

<%= link_to "Back to trips", trips_path %>

app/views/trips/index.html.erb
<h1> Trip Tracker</h1> 
<hr />

<% @trips.each do |trip| %>
  <div class='card center'>
    <h3>
      <%= link_to trip.name, trip_path(trip) %>
    </h3>

  </div>
<% end %>

<hr />

<button type='button'>
  <%= link_to 'Add a Trip', new_trip_path %>
</button>

app/views/trips/new.html.erb
<h1>Add a new trip</h1>
<hr />

<%= form_for @trip do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />
  <%= f.label :start_date %>
  <%= f.text_field :start_date, placeholder: 'DD/MM/YYYY' %>
  <br />
  <%= f.label :end_date %>
  <%= f.text_field :end_date, placeholder: 'DD/MM/YYYY' %>
  <br />
  <%= f.label :description%>
  <%= f.text_field :description %>
  <br />
  <%= f.submit %>
<% end %>

<%= link_to "Back to trips", trips_path %>

app/views/trips/show.html.erb
<h1><%= @trip.name %> Trip Recap</h1>
<hr />

<div class = "center">
  <h3><%= @trip.name %></h3>
  <p><small>Dates: <%= @trip.start_date %> through <%= @trip.end_date %></small></p>
  <p><%= @trip.description %></p>
  <footer> <small> <%= link_to 'Add Location', new_trip_location_path(@trip) %> </small> </footer>
<hr />


<footer>
  <small>
  <%= link_to 'Edit Trip', edit_trip_path(@trip) %>

  <%= link_to 'Delete Trip', trip_path(@trip), method: :delete %>
  </small>
</footer>

<br />

<%= link_to "Back to trips", trips_path %>
</div>